# Generated by Django 3.2.4 on 2021-06-19 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_name', models.CharField(max_length=200)),
                ('developer_location', models.CharField(max_length=200)),
                ('developer_fundation_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game_Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_format', models.CharField(max_length=100)),
                ('desc_format', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Game_Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=100)),
                ('desc_genre', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Game_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_status', models.CharField(max_length=100)),
                ('desc_status', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('platform_release_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=200)),
                ('publisher_location', models.CharField(max_length=200)),
                ('publisher_fundation_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_status', models.CharField(max_length=100)),
                ('desc_purchase_status', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=200)),
                ('game_release_date', models.DateField()),
                ('game_cover', models.CharField(max_length=200)),
                ('purchase_price', models.FloatField()),
                ('game_purchase_date', models.DateField()),
                ('developer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videogames.developer')),
                ('game_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videogames.game_format')),
                ('game_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videogames.game_status')),
                ('genre_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videogames.game_genre')),
                ('platform_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videogames.platform')),
                ('publisher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videogames.publisher')),
                ('purchase_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videogames.purchase_status')),
            ],
        ),
    ]
