# Generated by Django 3.2.4 on 2021-06-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogames', '0002_auto_20210626_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_genre',
            name='desc_genre',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
